CREATE SCHEMA IF NOT EXISTS `bd_cnbv` DEFAULT CHARACTER SET utf8;

CREATE TABLE IF NOT EXISTS `bd_cnbv`.`cnbv_empleados_aai` (
  `id_` INT NOT NULL AUTO_INCREMENT,
  `id_perfil_puesto` INT NULL,
  `numero_expediente` VARCHAR(4) NULL,
  `area` VARCHAR(10) NULL,
  `nombre` TEXT NULL,
  `apellido_paterno` TEXT NULL,
  `apellido_materno` TEXT NULL,
  `adscrito_oic` VARCHAR(2) NULL,
  `cargo` VARCHAR(100) NULL,
  `nivel` VARCHAR(100) NULL,
  `codigo_nivel` VARCHAR(100) NULL,
  `estatus` VARCHAR(100) NULL,
  `codigo_puesto` VARCHAR(40) NULL,
  `grado` VARCHAR(20) NULL,
  `competencias` TEXT NULL,
  `habilidades` TEXT NULL,
  `fecha_nacimiento` DATE NULL,
  `sexo` VARCHAR(2) NULL,
  `rfc` VARCHAR(13) NULL,
  `curp` VARCHAR(14) NULL,
  `lugar_nacimiento` VARCHAR(500) NULL,
  `nacionalidad` VARCHAR(45) NULL,
  `iniciales` VARCHAR(7) NULL,
  `correo_cnbv` VARCHAR(50) NULL,
  `correo_personal` VARCHAR(50) NULL,
  `celular` INT(12) NULL,
  `telefono` INT(12) NULL,
  `direccion` VARCHAR(250) NULL,
  `extension` INT(4) NULL,
  `torre` VARCHAR(15) NULL,
  `piso` INT(2) NULL,
  `coordenada` VARCHAR(3) NULL,
  `curriculum` VARCHAR(45) NULL,
  `estado_civil` VARCHAR(10) NULL,
  `cedula` VARCHAR(45) NULL,
  PRIMARY KEY (`id_`))
ENGINE = InnoDB;